### ISSUE TITLE
Refactor CLI options handling

### ISSUE THREAD

**Issue by ValentiWorkLearning** [MaksymPrymierov/life-game#14]
1. For a such logic it's better to use factory method and a cmd options parser.
https://github.com/MaksymPrymierov/life-game/blob/80753b9b85f0baf1bc3e25ebe6dc3de94ed29250/src/main.cpp#L47

2. For cmd parsing you can use booost::program_options for instance
3.  Try to avoid manual memory management. For your case std::unique_ptr seems suitable.

**Comment by MaksymPrymierov** [comment]
Done.
