### ISSUE TITLE
Exceptions adding

### ISSUE THREAD

**Issue by ValentiWorkLearning** [MaksymPrymierov/life-game#15]
It's quite unstraight way of handling class creation through getters validation . There are two possible approaches:
1. Use a kind of member method isValid() like in Qt Framework
2.  Use exceptions throwing when invalid parameters have been passed to c-tor
https://github.com/MaksymPrymierov/life-game/blob/80753b9b85f0baf1bc3e25ebe6dc3de94ed29250/test/screen_cli_test.cpp#L80

**Comment by MaksymPrymierov** [comment]
Thank you! I am going to rework all tests.

**Comment by MaksymPrymierov** [comment]
Done.
