### ISSUE TITLE
Let's use conan for dependencies management

### ISSUE THREAD

**Issue by ValentiWorkLearning** [MaksymPrymierov/life-game#16]
Conan is C++ package manager which allows to install and build C++ libraries without pain(almost),

https://github.com/MaksymPrymierov/life-game/blob/80753b9b85f0baf1bc3e25ebe6dc3de94ed29250/CMakeLists.txt#L5

Take a look at the examples in the repo examples. I guess, they will be suitable for you.
https://github.com/conan-io/cmake-conan1

**Comment by MaksymPrymierov** [comment]
Done.
