### ISSUE TITLE
Use pure virtual methods here

### ISSUE THREAD

**Issue by ValentiWorkLearning** [MaksymPrymierov/life-game#4]
https://github.com/MaksymPrymierov/life-game/blob/b2e4df09d409b8d4f227b93f6ca39bb53f524b84/src/screen.cpp#L26

**Comment by MaksymPrymierov** [comment]
Done https://github.com/MaksymPrymierov/life-game/commit/d7c5e9e963f894d43562239db778a7a861ded9e2.
