### ISSUE TITLE
Build directory

### ISSUE THREAD

**Issue by Alexander-Degtyar** [MaksymPrymierov/life-game#9]
https://github.com/MaksymPrymierov/life-game/blob/b2e4df09d409b8d4f227b93f6ca39bb53f524b84/README.md#L10-L12

Prefer to create build directory to encapsulate temporary files and make this process more user-friendly.
- `cd life-game`
- `mkdir build && cd build`
- `cmake ..`
- `cmake --build .`

**Comment by MaksymPrymierov** [comment]
Done.
